### ISSUE TITLE
Star number not updated

### ISSUE THREAD

**Issue by usoonees** [logseq/marketplace#180]
Marketplace star number
<img width="909" alt="image" src="https://user-images.githubusercontent.com/56818734/168472600-c84cfe79-2022-41e2-bcdd-6b3ead4f37a0.png">

Github star number
<img width="979" alt="image" src="https://user-images.githubusercontent.com/56818734/168472614-60fe9a57-6fbe-464c-adfd-f8c096801409.png">

**Comment by sawhney17** [comment]
The values are not real time they update intermittently. If you check now you'll see the value closer to the actual value.
