### ISSUE TITLE
why i call  await logseq.Editor.insertBlock method will produce two same block

### ISSUE THREAD

**Issue by micl9** [logseq/marketplace#224]
when i call this  `await logseq.Editor.insertBlock(targetBlock.uuid, '🚀 Fetching Gitee Issues ...', {before: true})` it will produce two block
<img width="254" alt="截屏2022-07-27 14 30 40" src="https://user-images.githubusercontent.com/38341571/181177200-42de8cdd-1f1e-4592-acd7-fc1802ff1342.png">

**Comment by sawhney17** [comment]
Perhaps you can try restarting logseq.

**Comment by micl9** [comment]
> Perhaps you can try restarting logseq.

not working , so is there any other settings? 
In my opinions, when I call this method, it only produces one output

**Comment by cnrpman** [comment]
Can you report this in the Logseq repo?

**Comment by micl9** [comment]
> Can you report this in the Logseq repo?

ok ,i will do this
