### ISSUE TITLE
Update readme to mention effect property in manifest.json

### ISSUE THREAD

**Issue by guypursey** [logseq/marketplace#227]
I read at a [Reddit post about plugin security](https://www.reddit.com/r/logseq/comments/w2cwpc/comment/igqr5tq/?utm_source=share&utm_medium=web2x&context=3) that setting `effect` to `true` in manifest.json ensures the package can make network calls -- and in turn this means that property's absence should reassure users that the plugin does not need to make network requests (in case there are any concerns about privacy/security).

But the `effect` property isn't mentioned in the marketplace repo readme.

**Comment by xyhp915** [comment]
Hi @guypursey We intend to do some optimizations of more granular control over the permissions of the plugin API. At that time, the use of `effect` will be better explained to developers and users.

**Comment by guypursey** [comment]
Thanks @xyhp915. That makes sense but is it worth including a line at least in the readme for now, just so people know in the meantime? Or is it the current use of the property more complicated than the description above?

**Comment by xyhp915** [comment]
> Thanks @xyhp915. That makes sense but is it worth including a line at least in the readme for now, just so people know in the meantime? Or is it the current use of the property more complicated than the description above?

Just be fixed in README file, although it is a simple explanation. As for the developer side, more documentation will follow as the plugin system is improved.

**Comment by guypursey** [comment]
Great. Thanks!
