### ISSUE TITLE
Process for deprecating a plugin?

### ISSUE THREAD

**Issue by mlanza** [logseq/marketplace#231]
I wrote a plugin and, later, an improved alternative for it which works differently.  I do not wish to support the former.  Is this just a pull request which deletes my previously added plugin?

I wasn't sure how doing this would affect the user experience.  Does my deleting a plugin cause it to be automatically uninstalled from user systems?

**Comment by sawhney17** [comment]
It won't cause it to be automatically uninstalled it will just make it impossible to update and install from the marketplace.

**Comment by mlanza** [comment]
So if the plugin is dropped from the plugins manifest, I guess it will persist in its last-installed version indefinitely or until the user uninstalls it.  And I'm guessing a users could still uninstall such a plugin.  If this is the case, it's safe to close this issue.  I just wanted to ensure that retracting a plugin wouldn't break someone's Logseq install in some odd way.
