### ISSUE TITLE
Enabling plugins without html is broken

### ISSUE THREAD

**Issue by DimitryDushkin** [logseq/marketplace#262]
It cannot create entry upon plugin import. The error is
```
instrument.js:112 [Load Plugin Error]  Error: Not existed method #write_dotdir_file
```

Looks like it tries to add index.html from built-in template anyways, but fails to write it to file system.

**Comment by cnrpman** [comment]
@xyhp915

**Comment by Bad3r** [comment]
@xyhp915 should this remain open?
