### ISSUE TITLE
admonition-panels seem to no longer exist

### ISSUE THREAD

**Issue by YU000jp** [logseq/marketplace#347]
https://github.com/Zyrohex/admonition-panels

**Comment by CharlesChiuGit** [comment]
Can confirmed

**Comment by CharlesChiuGit** [comment]
Seems like the author had deleted the repo.

**Comment by YU000jp** [comment]
close https://github.com/logseq/marketplace/commit/b3201f7e2c8c5cd5913ef044877510ff39630b27
