### ISSUE TITLE
Installation issues with the latest logseq release

### ISSUE THREAD

**Issue by tobealive** [logseq/marketplace#367]
With the latest releases, users are encountering.

```
[Error]<logseq-allday-theme> :release-channel-issue "Github API Failed(404) {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/repos#get-the-latest-release\"}"]
```

I tried to investigate but couldn't find an issue on my side. Since nothing changed and other themes or plugins that hold the same pattern continue to work, I assume it must be an upstream issue. is there anything I can do on my side?

Related: https://github.com/tobealive/logseq-allday-theme/issues/19

**Comment by CharlesChiuGit** [comment]
Can confirm on 0.9.2
