### ISSUE TITLE
Abandoning logseq-dynamic-lookup, update to a fork?

### ISSUE THREAD

**Issue by peanball** [logseq/marketplace#584]
Dear all,

I've not been using logseq for a while now and I'm abandoning my `logseq-dynamic-lookup` plugin. Without using it, I can't ensure that the version bumps make it keep working.

There is a fork by @jjaychen1e. Maybe they want to take over?

If not, I will add a PR to remove the plugin from the marketplace.

**Comment by jjaychen1e** [comment]
Sorry, I have not been using Logseq personally for a while.
