### ISSUE TITLE
How a theme update reaches the marketplace?

### ISSUE THREAD

**Issue by tobealive** [logseq/marketplace#69]
Hello :)
I updated my theme, but I'm not sure how to proceed.
What would be the necessary steps to the update gets into the marketplace?
I hope that question is not too dumb 😅

Sending love and blessings 🙏

**Comment by sawhney17** [comment]
Simply update the version number on your package.json file. You don't need any more work on your part.

**Comment by tobealive** [comment]
Hi @sawhney17 
Thanks again to you  🙂!
